#' Generate reference expression profile from sc-level data
#'
#' This function generates reference expression profile from single-cell level expression data,
#' which will be applied in the following niche-effect estimation steps.
#'
#' @param sc_count Expression matrix for single-cell level data.
#' @param label A vector of cell labels for all cells in the sc_count.
#' @param normalize Logical. Whether do normalization on sc_count. Default is TRUE.
#' @examples
#' data(sc_count)
#' data(sc_label)
#' ref_celltype_count<-generate_ref_celltype_gep(sc_count = sc_count, label = sc_label)
#' @import Seurat
#' @export
generate_ref_celltype_gep<-function(sc_count,label,normalize=T){
  sc<-CreateSeuratObject(sc_count)
  sc$celltype<-sc_label
  type<-as.character(unique(label))
  ref_celltype_gep<-matrix(nrow = nrow(sc),ncol = length(type))
  row.names(ref_celltype_gep)<-row.names(sc)
  colnames(ref_celltype_gep)<-type
  if (normalize==T){
    sc<-NormalizeData(sc)
    for (i in type) {
      ref_celltype_gep[,i]<-apply(sc@assays$RNA$data[,which(sc$celltype==i)],1,mean)
    }
  } else {
    for (i in type) {
      ref_celltype_gep[,i]<-apply(sc@assays$RNA$counts[,which(sc$celltype==i)],1,mean)
    }
  }

  return(ref_celltype_gep)
}

#' Generate reference expression profile for cell type's marker genes
#'
#' This function generates reference expression profile for marker genes significantly unregulated
#' in each cell type, which will be applied in the following cell-type deconvolution step.
#' @param ref_celltype_gep The reference expression profile which is generated by `generate_ref_celltype_gep()`.
#' @param sc_count Expression matrix for single-cell level data.
#' @param label A vector of cell labels for all cells in the sc_count.
#' @param max_p The threshold of p-value used for extracting significantly upregulated marker genes for cell types.
#' @param top_count Number of marker genes selected for each cell type.
#' @examples
#' data(sc_count)
#' data(sc_label)
#' ref_celltype_count<-generate_ref_celltype_gep(sc_count = sc_count, label = sc_label)
#' marker_ref_celltype_count<-generate_marker_celltype_gep(ref_celltype_gep = ref_celltype_count, sc_count = sc_count, label = sc_label)
#' @import Seurat
#' @import dplyr
#' @export
generate_marker_celltype_gep<-function(ref_celltype_gep,sc_count,label,max_p=1e-30,top_count=100){
  sc<-CreateSeuratObject(sc_count)
  sc$celltype<-sc_label
  type<-as.character(unique(label))
  Idents(sc)<-sc$celltype
  sc<-NormalizeData(sc)
  markers<-FindAllMarkers(sc,only.pos = T)
  select_markers<-markers %>% group_by(cluster) %>% top_n(n = top_count, wt = avg_log2FC)
  select_markers<-select_markers[which(select_markers$p_val_adj<max_p),]
  marker_ref_celltype_gep<-ref_celltype_gep[select_markers$gene,]

  return(marker_ref_celltype_gep)
}

